### ISSUE TITLE
VIP KYC and Claim Views

### ISSUE THREAD

**Issue by silviopaganini** [pigzbe/pigzbe-app#27]
- [ ] Intro screen
- [ ] Name / DOB / email screen
- [ ] Nationality etc screen
- [ ] Address screen with lookup and confirmation
- [ ] Address screen with manual entry
- [ ] Previous addresses screen
- [ ] Details check progress
- [ ] Identity check screen (take picture of ID)
- [ ] Identity check success screeen
- [ ] Unique code entry screen
- [ ] SMS message send screen
- [ ] SMS message entry screen
- [ ] Wollo claim screen

**Comment by ianmcgregor** [comment]
TODO: Find out if we need KYC for the actual product or if it's just for the ICO
