### ISSUE TITLE
UI Elements (anything related to components and interface) 

### ISSUE THREAD

**Issue by silviopaganini** [pigzbe/pigzbe-app#6]

**Comment by ianmcgregor** [comment]
- [ ] Add font weights
- [ ] Button component
- [ ] Input component
- [ ] Reusable text styles
- [ ] Tab bar menu with icons
- [ ] Checkbox component
- [ ] Add image button
- [ ] Conversion Icons
- [ ] Peeking pig
- [ ] Settings button
- [ ] New messages tab button state
